### PR TITLE
Complete react capstone project

### PR DESCRIPTION
**Pull request by Rudy-Menekam**
- Selected the API to use.
- Build file structure for React app.
- Prepare routes and navigation in your app.
- Display a list of items and filter them from the API.
- Create tests
- Style components
- Deploy on netlify
- Record loom video

### CODE REVIEW

**Review by ishimwezachee — CHANGES_REQUESTED** [review]
Hi @Rudy-Menekam , 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!
image

## Highlights 
All linters are passing ✔️
Correct use of GitFlow ✔️
Project is running successfully ✔️

## Suggested changes

- [x]   You have done a great job for your project miss a very small changes to complete. You are supposed to follow the [design guideline](https://www.behance.net/gallery/31579789/Ballhead-App-(Free-PSDs)) such as Typography: `font face, size, and weight` as it is provide from the design. please consider using fonts like lato, gill sans so that your design typograph can look similar to the one provided from the design. 

- [ ]  You should perform a mocking data fetching and Redux Store connection, not just direct using redux and redux store itself through your tests

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by Rudy-Menekam** [comment]
@ishimwezachee please i don't understand your second point

**Review by omar-muhamad — CHANGES_REQUESTED** [review]
# Changes Required ♻️
### Hi @Rudy-Menekam,

#### Nice job making the required changes. Unfortunately, you missed some of them but you are almost there.



## (Highlights) Good Points: :+1:
- Your work is well documented. ✔
- The correct workflow is used.  ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- [ ] As required by the previous reviewer, and as per those [test requirements](https://github.com/microverseinc/curriculum-react-redux/blob/main/capstone/react_capstone.md#:~:text=the%20home%20page.-,Testing%20requirements,-Create%20unit%20tests) Please add tests to mock the access to the API, so that your tests don't send actual requests as you did. and you need to mock the connection to the Redux Store not directly using the store as you did.

[Hint] Kindly see these videos may help:
https://www.youtube.com/watch?v=8Qfz5EFG9gQ
https://www.youtube.com/watch?v=TBZy-Rc-xX0 

## [Optional] suggestions:

- Nothing to mention.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Review by BenMukebo — APPROVED** [review]
# Status: Approved  :champagne:  ✔️:confetti_ball: 

## Hi @Rudy-Menekam, 

### **Congratulations! 🎉 Project Approved ✅**

Good job so far. Well Done.👍🏻 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 


### To Highlight 🎉
- No linter errors. :heavy_check_mark:
- Git flow is followed. :heavy_check_mark:
- Good presentation video. ✔️ 
- Your app has been well deployed. 🥇 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers :clinking_glasses:  and Happy coding!!! :dancers:💻  

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me @BenMukebo when you comment so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
